# Makefile for examples week-11

all: lab11 maptest

maptest: maptest.c
	gcc maptest.c -Wall -omaptest -lpthread

lab11: lab11.c
	gcc lab11.c -Wall -olab11 -lpthread

clean:
	rm -f *.o lab11 maptest

